import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Categories } from "../components/Categories";
import { Featured } from "../components/Featured";
import Hero from "../components/Hero";
import { Product } from "../types";
import { apiStoreUrl } from "../utils/db";

const Home: NextPage<{ products: Product[]; categories: any }> = ({
  products,
  categories,
}) => {
  return (
    <div className="home">
      <Head>
        <title>Urbanik Store</title>
        {/* </Head><meta name='description' content='Generated by create next app' /> */}

        <meta property="og:title" content="Urbanik Store" />
        <meta
          property="og:description"
          content="Low price high quality items at your hands"
        />
        <meta property="og:type" content="eccomerce" />
        <meta property="og:url" content="https://next-shop-livid.vercel.app/" />
        <meta
          property="og:image"
          content="https://inspirationseek.com/wp-content/uploads/2016/02/Cute-Dog-Images.jpg"
        />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Hero />
      <Featured products={products} />
      <section id="filler" className="w-full h-full relative">
        <div className="absolute top-1/2 right-1/2">
          <h1 className="text-white text-base italic">
            Clothes made for humans, by humans.
          </h1>
          <h1 className="text-white text-sm italic text-right">
            - Ulysses F. Oscar
          </h1>
        </div>
        <div className="w-full h-[30rem]">
          <img
            className="object-cover object-center w-full h-full"
            src="https://images.unsplash.com/photo-1542060748-10c28b62716f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
          />
        </div>
      </section>
      <Categories categories={categories} />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  try {
    const res = await fetch(apiStoreUrl + "/products/");
    const products = await res.json();

    const getCategories = await fetch(apiStoreUrl + "/products/categories");
    const categories = await getCategories.json();
    return {
      props: {
        products: products?.data,
        categories: categories?.data,
      },
    };
  } catch (error) {
    return { notFound: true };
  }
};

export default Home;
