import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ProductCard from '../components/ProductCard'
import styles from '../styles/Home.module.css'
import { Product } from '../types'

const Home: NextPage<{products: Product[]}> = ({ products }) => {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full text-center py-20'>
        <h1 className='text-6xl font-bold'>Welcome noob</h1>
        <p className='text-lg'>Shop now to be stronger than ever.</p>
      </div>
      <div className='flex flex-wrap gap-4'>
        { products.map(product => {
          return(
            <ProductCard key={product.id} product={product} />
          )
        })}

      </div>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async(context) => {
  const res = await fetch("https://fakestoreapi.com/products/");
  const products = await res.json()
  
  return {
    props: {
      products
    }
  }
}

export default Home
